services:
  django: &django
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: AiR_Notes_server_prod_django
    ports:
      - 8000:8000 # app server port
    volumes:
      - ../media:/app/media
    environment:
      DEBUG: 0 # Should be set to 0 in production !
      PROD: 1
      DJANGO_ALLOWED_HOSTS: 127.0.0.1, localhost
      DJANGO_CSRF_TRUSTED_ORIGINS: "https://AiR_Notes_server.valegreg.com"
      ENFORCE_HTTPS: 1 # Should be set to 1 in production !
      DATABASE_ENGINE: mysql
      DATABASE_NAME: dbdjango
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: monpassword
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
