FROM buildpack-deps:trixie

WORKDIR /app

# Install uv (Python Manager)
COPY --from=ghcr.io/astral-sh/uv:0.10 /uv /uvx /bin/

# System dependencies for Django/MariaDB
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID --shell /bin/bash -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

COPY .python-version /app/

# Pre-install default versions so the container is ready to go
RUN uv python install
