# Generated by Django 5.2.15 on 2026-06-10 15:27

import django.db.models.deletion
import notes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('TXT', 'Text Note'), ('IMA', 'Image Note'), ('ARR', 'Arrow Note')], max_length=3)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArrowNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('pos_z', models.FloatField(default=0.0)),
                ('pos2_x', models.FloatField(default=0.0)),
                ('pos2_y', models.FloatField(default=0.0)),
                ('pos2_z', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
            bases=('notes.note', models.Model),
        ),
        migrations.CreateModel(
            name='ImageNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('pos_z', models.FloatField(default=0.0)),
                ('rot_x', models.FloatField(default=0.0)),
                ('rot_y', models.FloatField(default=0.0)),
                ('rot_z', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to=notes.models.image_filename)),
                ('anchored', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('notes.note', models.Model),
        ),
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('pos_z', models.FloatField(default=0.0)),
                ('rot_x', models.FloatField(default=0.0)),
                ('rot_y', models.FloatField(default=0.0)),
                ('rot_z', models.FloatField(default=0.0)),
                ('content', models.TextField()),
                ('anchored', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('notes.note', models.Model),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional name for the QR code location/item', max_length=150)),
                ('share_status', models.CharField(choices=[('PR', 'Privé'), ('GR', 'Ouvert au visionnage'), ('OP', "Ouvert à l'édition")], default='PR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QRcodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='qrcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.qrcode'),
        ),
    ]
