# Generated by Django 5.2.15 on 2026-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='share_status',
            field=models.CharField(choices=[('PRIVATE', 'Privé'), ('OPEN_VIEW', 'Ouvert au visionnage'), ('OPEN_EDIT', "Ouvert à l'édition")], default='PRIVATE', max_length=10),
        ),
    ]
